# Generated by Django 4.0.3 on 2022-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-04-23'),
            preserve_default=False,
        ),
    ]
